use super::*;

pub(super) const WORKFLOW_STEP_DEFS: &[WorkflowStepDefinition] = &[
    WorkflowStepDefinition { op: "time_series_v1", handler: workflow_time_series_v1_handler },
    WorkflowStepDefinition { op: "stats_v1", handler: workflow_stats_v1_handler },
    WorkflowStepDefinition { op: "entity_linking_v1", handler: workflow_entity_linking_v1_handler },
    WorkflowStepDefinition { op: "table_reconstruct_v1", handler: workflow_table_reconstruct_v1_handler },
    WorkflowStepDefinition { op: "lineage_v2", handler: workflow_lineage_v2_handler },
    WorkflowStepDefinition { op: "lineage_v3", handler: workflow_lineage_v3_handler },
    WorkflowStepDefinition { op: "rule_simulator_v1", handler: workflow_rule_simulator_v1_handler },
    WorkflowStepDefinition { op: "constraint_solver_v1", handler: workflow_constraint_solver_v1_handler },
    WorkflowStepDefinition { op: "chart_data_prep_v1", handler: workflow_chart_data_prep_v1_handler },
    WorkflowStepDefinition { op: "diff_audit_v1", handler: workflow_diff_audit_v1_handler },
    WorkflowStepDefinition { op: "vector_index_v1_build", handler: workflow_vector_index_v1_build_handler },
    WorkflowStepDefinition { op: "vector_index_v1_search", handler: workflow_vector_index_v1_search_handler },
    WorkflowStepDefinition { op: "evidence_rank_v1", handler: workflow_evidence_rank_v1_handler },
    WorkflowStepDefinition { op: "fact_crosscheck_v1", handler: workflow_fact_crosscheck_v1_handler },
    WorkflowStepDefinition { op: "timeseries_forecast_v1", handler: workflow_timeseries_forecast_v1_handler },
    WorkflowStepDefinition { op: "finance_ratio_v1", handler: workflow_finance_ratio_v1_handler },
    WorkflowStepDefinition { op: "anomaly_explain_v1", handler: workflow_anomaly_explain_v1_handler },
    WorkflowStepDefinition { op: "template_bind_v1", handler: workflow_template_bind_v1_handler },
    WorkflowStepDefinition { op: "provenance_sign_v1", handler: workflow_provenance_sign_v1_handler },
    WorkflowStepDefinition { op: "query_lang_v1", handler: workflow_query_lang_v1_handler },
    WorkflowStepDefinition { op: "columnar_eval_v1", handler: workflow_columnar_eval_v1_handler },
    WorkflowStepDefinition { op: "stream_window_v1", handler: workflow_stream_window_v1_handler },
    WorkflowStepDefinition { op: "stream_window_v2", handler: workflow_stream_window_v2_handler },
    WorkflowStepDefinition { op: "sketch_v1", handler: workflow_sketch_v1_handler },
    WorkflowStepDefinition { op: "explain_plan_v1", handler: workflow_explain_plan_v1_handler },
    WorkflowStepDefinition { op: "explain_plan_v2", handler: workflow_explain_plan_v2_handler },
    WorkflowStepDefinition { op: "optimizer_v1", handler: workflow_optimizer_v1_handler },
];
