const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

function readText(relPath) {
  return fs.readFileSync(path.resolve(__dirname, "../../..", relPath), "utf8");
}

test("ci check publishes architecture scorecard outputs", () => {
  const ciCheck = readText("ops/scripts/ci_check.ps1");
  const verification = readText("docs/verification.md");

  assert.match(ciCheck, /architecture_scorecard_latest\.json/);
  assert.match(ciCheck, /architecture_scorecard_latest\.md/);
  assert.match(ciCheck, /architecture_scorecard_release_ready_latest\.json/);
  assert.match(ciCheck, /architecture_scorecard_release_ready_latest\.md/);
  assert.match(ciCheck, /workflow_contract_sync/);
  assert.match(ciCheck, /governance_control_plane_boundary/);
  assert.match(ciCheck, /authoring_rejected_unknown_type/);
  assert.match(ciCheck, /preflight_unknown_type_guided/);
  assert.match(ciCheck, /authoring surface no longer rejects unknown node types/);
  assert.match(ciCheck, /preflight no longer emits unknown node type guidance/);
  assert.match(ciCheck, /check_governance_control_plane_boundary\.ps1/);
  assert.match(ciCheck, /governance_capabilities\.v1\.json/);
  assert.match(ciCheck, /workflow_governance_capabilities\.generated\.js/);
  assert.match(ciCheck, /GovernanceCapabilities\.Generated\.cs/);
  assert.match(ciCheck, /lifecycle_mutation_allowed/);
  assert.match(ciCheck, /uncovered governance routes/);
  assert.match(ciCheck, /duplicate owned route prefixes/);
  assert.match(ciCheck, /governance capability manifest capability drift/);
  assert.match(ciCheck, /desktop governance capability generated drift/);
  assert.match(ciCheck, /winui governance capability generated drift/);
  assert.match(ciCheck, /governance capability generated source authority drift/);
  assert.match(ciCheck, /governance_store_schema_versions/);
  assert.match(ciCheck, /check_governance_store_schema_versions\.ps1/);
  assert.match(ciCheck, /source modules missing schema_version/);
  assert.match(ciCheck, /runtime outputs missing schema_version/);
  assert.match(ciCheck, /local_workflow_store_schema_versions/);
  assert.match(ciCheck, /check_local_workflow_store_schema_versions\.ps1/);
  assert.match(ciCheck, /legacy workflow queue migration missing/);
  assert.match(ciCheck, /legacy template marketplace migration missing/);
  assert.match(ciCheck, /template_pack_contract_sync/);
  assert.match(ciCheck, /check_template_pack_contract_sync\.ps1/);
  assert.match(ciCheck, /legacy template pack import migration missing/);
  assert.match(ciCheck, /exported artifact schema drift/);
  assert.match(ciCheck, /local_template_storage_contract_sync/);
  assert.match(ciCheck, /check_local_template_storage_contract_sync\.ps1/);
  assert.match(ciCheck, /legacy local template storage migration missing/);
  assert.match(ciCheck, /saveCurrentAsTemplate no longer writes versioned storage/);
  assert.match(ciCheck, /offline_template_catalog_sync/);
  assert.match(ciCheck, /check_offline_template_catalog_sync\.ps1/);
  assert.match(ciCheck, /legacy office theme migration missing/);
  assert.match(ciCheck, /offline engine cleaning template registry is empty/);
  assert.match(ciCheck, /node_config_contracts\.v1\.json/);
  assert.match(ciCheck, /rust authority drift/);
  assert.match(ciCheck, /glue validation client drift/);
  assert.match(ciCheck, /generated desktop helper files still present/);
  assert.match(ciCheck, /node_config_schema_coverage/);
  assert.match(ciCheck, /local_node_catalog_policy/);
  assert.match(ciCheck, /check_node_config_schema_coverage\.ps1/);
  assert.match(ciCheck, /check_local_node_catalog_policy\.ps1/);
  assert.match(ciCheck, /nested_shape_constrained/);
  assert.match(ciCheck, /required_nested_missing/);
  assert.match(ciCheck, /nested_shape_constrained_deficit/);
  assert.match(ciCheck, /missing required nested node coverage/);
  assert.match(ciCheck, /rust_authority=/);
  assert.match(ciCheck, /operator_catalog_sync/);
  assert.match(ciCheck, /schema_path/);
  assert.match(ciCheck, /desktop_module_path/);
  assert.match(ciCheck, /renderer_module_path/);
  assert.match(ciCheck, /manifest_missing_operators/);
  assert.match(ciCheck, /manifest_metadata_drift/);
  assert.match(ciCheck, /desktop_module_metadata_drift/);
  assert.match(ciCheck, /renderer_module_drift/);
  assert.match(ciCheck, /missing_palette_section_domains/);
  assert.match(ciCheck, /stale_pinned_operators/);
  assert.match(ciCheck, /duplicate_pinned_operators/);
  assert.match(ciCheck, /missing_presentation_operators/);
  assert.match(ciCheck, /stale_presentation_operators/);
  assert.match(ciCheck, /invalid_presentation_entries/);
  assert.match(ciCheck, /missing_catalog_group_entries/);
  assert.match(ciCheck, /missing_catalog_policy_section_entries/);
  assert.match(ciCheck, /missing_section_types/);
  assert.match(ciCheck, /stale_catalog_types/);
  assert.match(ciCheck, /catalog_metadata_drift/);
  assert.match(ciCheck, /missing_desktop_exposable_in_catalog/);
  assert.match(ciCheck, /missing_desktop_exposable_in_routing/);
  assert.match(ciCheck, /missing_published_in_catalog/);
  assert.match(ciCheck, /missing_published_in_routing/);
  assert.match(ciCheck, /stale_catalog_operators/);
  assert.match(ciCheck, /checked-in manifest missing Rust operators/);
  assert.match(ciCheck, /desktop rust operator manifest module missing desktop-exposable operators/);
  assert.match(ciCheck, /rust operator palette policy missing domains/);
  assert.match(ciCheck, /rust operator palette pinned order has stale operators/);
  assert.match(ciCheck, /rust operator presentations missing desktop-exposable operators/);
  assert.match(ciCheck, /desktop defaults catalog missing Rust operator groups/);
  assert.match(ciCheck, /desktop defaults catalog missing Rust operator policy sections/);
  assert.match(ciCheck, /local node presentations missing node types/);
  assert.match(ciCheck, /defaults catalog local node metadata drift/);
  assert.match(ciCheck, /desktop defaults catalog missing desktop-exposable Rust operators/);
  assert.match(ciCheck, /desktop rust routing missing desktop-exposable Rust operators/);
  assert.match(ciCheck, /defaults catalog missing published Rust operators/);
  assert.match(ciCheck, /desktop rust routing missing published Rust operators/);
  assert.match(ciCheck, /frontend_primary_verification/);
  assert.match(ciCheck, /frontend_compatibility_verification/);

  assert.match(verification, /architecture_scorecard_latest\.json/i);
  assert.match(verification, /architecture_scorecard_latest\.md/i);
  assert.match(verification, /architecture_scorecard_release_ready_latest\.json/i);
  assert.match(verification, /architecture_scorecard_release_ready_latest\.md/i);
  assert.match(verification, /check_workflow_contract_sync\.ps1/i);
  assert.match(verification, /check_governance_control_plane_boundary\.ps1/i);
  assert.match(verification, /governance control plane boundary/i);
  assert.match(verification, /lifecycle_mutation_allowed/i);
  assert.match(verification, /governance_capabilities\.v1\.json/i);
  assert.match(verification, /export_governance_capabilities\.ps1/i);
  assert.match(verification, /workflow_governance_capabilities\.generated\.js/i);
  assert.match(verification, /GovernanceCapabilities\.Generated\.cs/i);
  assert.match(verification, /authoring_rejected_unknown_type/i);
  assert.match(verification, /preflight_unknown_type_guided/i);
  assert.match(verification, /check_governance_store_schema_versions\.ps1/i);
  assert.match(verification, /governance store schema version/i);
  assert.match(verification, /check_local_workflow_store_schema_versions\.ps1/i);
  assert.match(verification, /local workflow store schema version/i);
  assert.match(verification, /check_template_pack_contract_sync\.ps1/i);
  assert.match(verification, /template pack contract/i);
  assert.match(verification, /template_pack_artifact\.schema\.json/i);
  assert.match(verification, /check_local_template_storage_contract_sync\.ps1/i);
  assert.match(verification, /local template storage contract/i);
  assert.match(verification, /local_template_storage\.schema\.json/i);
  assert.match(verification, /check_offline_template_catalog_sync\.ps1/i);
  assert.match(verification, /offline template catalog/i);
  assert.match(verification, /office_theme_catalog\.schema\.json/i);
  assert.match(verification, /office_layout_catalog\.schema\.json/i);
  assert.match(verification, /cleaning_template_registry\.schema\.json/i);
  assert.match(verification, /node_config_contracts\.v1\.json/i);
  assert.match(verification, /workflow_validation_client\.py/i);
  assert.match(verification, /workflow_contract\.rs/i);
  assert.match(verification, /check_node_config_schema_coverage\.ps1/i);
  assert.match(verification, /check_local_node_catalog_policy\.ps1/i);
  assert.match(verification, /export_operator_manifest\.ps1/i);
  assert.match(verification, /check_operator_catalog_sync\.ps1/i);
  assert.match(verification, /operators_manifest\.v1\.json/i);
  assert.match(verification, /operators_manifest\.schema\.json/i);
  assert.match(verification, /rust_operator_manifest\.generated\.js/i);
  assert.match(verification, /renderer\/workflow\/rust_operator_manifest\.generated\.js/i);
  assert.match(verification, /rust-operator-presentations\.js/i);
  assert.match(verification, /rust-operator-palette-policy\.js/i);
  assert.match(verification, /nested_shape_constrained/i);
  assert.match(verification, /required nested/i);
  assert.match(verification, /published Rust operator/i);
  assert.match(verification, /release-ready scorecard/i);
});
