const { contextBridge, ipcRenderer, webUtils } = require("electron");

contextBridge.exposeInMainWorld("aiwfDesktop", {
  getConfig: () => ipcRenderer.invoke("aiwf:getConfig"),
  saveConfig: (cfg) => ipcRenderer.invoke("aiwf:saveConfig", cfg),
  health: (cfg) => ipcRenderer.invoke("aiwf:health", cfg),
  listCleaningTemplates: () => ipcRenderer.invoke("aiwf:listCleaningTemplates"),
  precheckCleaning: (payload, cfg) => ipcRenderer.invoke("aiwf:precheckCleaning", payload, cfg),
  runCleaning: (payload, cfg) => ipcRenderer.invoke("aiwf:runCleaning", payload, cfg),
  runWorkflow: (payload, cfg) => ipcRenderer.invoke("aiwf:runWorkflow", payload, cfg),
  enqueueWorkflowTask: (req) => ipcRenderer.invoke("aiwf:enqueueWorkflowTask", req),
  listWorkflowQueue: (req) => ipcRenderer.invoke("aiwf:listWorkflowQueue", req),
  getWorkflowQueueControl: () => ipcRenderer.invoke("aiwf:getWorkflowQueueControl"),
  setWorkflowQueueControl: (req) => ipcRenderer.invoke("aiwf:setWorkflowQueueControl", req),
  cancelWorkflowTask: (req) => ipcRenderer.invoke("aiwf:cancelWorkflowTask", req),
  retryWorkflowTask: (req) => ipcRenderer.invoke("aiwf:retryWorkflowTask", req),
  listWorkflowRuns: (opts) => ipcRenderer.invoke("aiwf:listWorkflowRuns", opts),
  listWorkflowVersions: (req) => ipcRenderer.invoke("aiwf:listWorkflowVersions", req),
  restoreWorkflowVersion: (req) => ipcRenderer.invoke("aiwf:restoreWorkflowVersion", req),
  compareWorkflowVersions: (req) => ipcRenderer.invoke("aiwf:compareWorkflowVersions", req),
  getWorkflowNodeCacheStats: () => ipcRenderer.invoke("aiwf:getWorkflowNodeCacheStats"),
  clearWorkflowNodeCache: () => ipcRenderer.invoke("aiwf:clearWorkflowNodeCache"),
  publishWorkflowApp: (req) => ipcRenderer.invoke("aiwf:publishWorkflowApp", req),
  listWorkflowApps: (req) => ipcRenderer.invoke("aiwf:listWorkflowApps", req),
  runWorkflowApp: (req, cfg) => ipcRenderer.invoke("aiwf:runWorkflowApp", req, cfg),
  getWorkflowRunTimeline: (req) => ipcRenderer.invoke("aiwf:getWorkflowRunTimeline", req),
  getWorkflowFailureSummary: (req) => ipcRenderer.invoke("aiwf:getWorkflowFailureSummary", req),
  getWorkflowSandboxAlerts: (req) => ipcRenderer.invoke("aiwf:getWorkflowSandboxAlerts", req),
  getWorkflowSandboxAlertRules: () => ipcRenderer.invoke("aiwf:getWorkflowSandboxAlertRules"),
  setWorkflowSandboxAlertRules: (req) => ipcRenderer.invoke("aiwf:setWorkflowSandboxAlertRules", req),
  muteWorkflowSandboxAlert: (req) => ipcRenderer.invoke("aiwf:muteWorkflowSandboxAlert", req),
  listWorkflowSandboxRuleVersions: (req) => ipcRenderer.invoke("aiwf:listWorkflowSandboxRuleVersions", req),
  compareWorkflowSandboxRuleVersions: (req) => ipcRenderer.invoke("aiwf:compareWorkflowSandboxRuleVersions", req),
  rollbackWorkflowSandboxRuleVersion: (req) => ipcRenderer.invoke("aiwf:rollbackWorkflowSandboxRuleVersion", req),
  getWorkflowSandboxAutoFixState: () => ipcRenderer.invoke("aiwf:getWorkflowSandboxAutoFixState"),
  listWorkflowSandboxAutoFixActions: (req) => ipcRenderer.invoke("aiwf:listWorkflowSandboxAutoFixActions", req),
  exportWorkflowSandboxPreset: (req) => ipcRenderer.invoke("aiwf:exportWorkflowSandboxPreset", req),
  importWorkflowSandboxPreset: (req) => ipcRenderer.invoke("aiwf:importWorkflowSandboxPreset", req),
  listWorkflowQualityGateReports: (req) => ipcRenderer.invoke("aiwf:listWorkflowQualityGateReports", req),
  exportWorkflowQualityGateReports: (req) => ipcRenderer.invoke("aiwf:exportWorkflowQualityGateReports", req),
  exportWorkflowSandboxAuditReport: (req) => ipcRenderer.invoke("aiwf:exportWorkflowSandboxAuditReport", req),
  listWorkflowAuditLogs: (req) => ipcRenderer.invoke("aiwf:listWorkflowAuditLogs", req),
  replayWorkflowRun: (req, cfg) => ipcRenderer.invoke("aiwf:replayWorkflowRun", req, cfg),
  compareWorkflowRuns: (req) => ipcRenderer.invoke("aiwf:compareWorkflowRuns", req),
  exportCompareReport: (req) => ipcRenderer.invoke("aiwf:exportCompareReport", req),
  listManualReviews: () => ipcRenderer.invoke("aiwf:listManualReviews"),
  listManualReviewHistory: (req) => ipcRenderer.invoke("aiwf:listManualReviewHistory", req),
  exportManualReviewHistory: (req) => ipcRenderer.invoke("aiwf:exportManualReviewHistory", req),
  submitManualReview: (req) => ipcRenderer.invoke("aiwf:submitManualReview", req),
  getWorkflowDiagnostics: (opts) => ipcRenderer.invoke("aiwf:getWorkflowDiagnostics", opts),
  saveWorkflow: (graph, name, opts) => ipcRenderer.invoke("aiwf:saveWorkflow", graph, name, opts),
  loadWorkflow: (opts) => ipcRenderer.invoke("aiwf:loadWorkflow", opts),
  openWorkflowStudio: () => ipcRenderer.invoke("aiwf:openWorkflowStudio"),
  openPath: (p) => ipcRenderer.invoke("aiwf:openPath", p),
  logRouteMetrics: (payload) => ipcRenderer.invoke("aiwf:logRouteMetrics", payload),
  getRouteMetricsSummary: () => ipcRenderer.invoke("aiwf:getRouteMetricsSummary"),
  inspectEncoding: (paths) => ipcRenderer.invoke("aiwf:inspectEncoding", paths),
  normalizeEncoding: (paths) => ipcRenderer.invoke("aiwf:normalizeEncoding", paths),
  checkFonts: () => ipcRenderer.invoke("aiwf:checkFonts"),
  installBundledFonts: () => ipcRenderer.invoke("aiwf:installBundledFonts"),
  checkRuntime: () => ipcRenderer.invoke("aiwf:checkRuntime"),
  startupSelfCheck: (cfg) => ipcRenderer.invoke("aiwf:startupSelfCheck", cfg),
  getTaskStoreStatus: (cfg) => ipcRenderer.invoke("aiwf:getTaskStoreStatus", cfg),
  getDroppedFilePath: (file) => {
    try {
      const p = webUtils.getPathForFile(file);
      if (p) return String(p);
    } catch {}
    try {
      if (file && typeof file.path === "string" && file.path.trim()) return String(file.path);
    } catch {}
    return "";
  },
});
