param(
  [string]$SqlHost = "127.0.0.1",
  [int]$SqlPort = 1433,
  [string]$DbName = "AIWF",
  [string]$SaUser = "sa",
  [Parameter(Mandatory=$true)]
  [string]$SaPassword,

  [string]$AppUser = "aiwf_app",
  [string]$AppPassword = "AIWF_Str0ng!Pass_2026",

  [string]$Root = "",
  [string]$Bus = "",
  [string]$Lake = "",

  [string]$DifyBaseUrl = "http://127.0.0.1:18080",
  [string]$DifyApiKey = "",
  [string]$LlmModel = "",
  [string]$LlmApiKey = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Info($m){ Write-Host "[INFO] $m" -ForegroundColor Cyan }
function Ok($m){ Write-Host "[ OK ] $m" -ForegroundColor Green }
function Warn($m){ Write-Host "[WARN] $m" -ForegroundColor Yellow }

if (-not $Root) {
  $Root = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
}
if (-not $Bus) {
  $Bus = if ($env:AIWF_BUS -and $env:AIWF_BUS.Trim()) { $env:AIWF_BUS.Trim() } else { Join-Path $Root "bus" }
}
if (-not $Lake) {
  $Lake = Join-Path $Root "lake"
}

function Ensure-Dir([string]$Path) {
  if (-not (Test-Path $Path)) { New-Item -ItemType Directory -Force -Path $Path | Out-Null }
}

function Write-Utf8NoBomFile([string]$Path, [string]$Content) {
  $dir = Split-Path -Parent $Path
  Ensure-Dir $dir
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

# -------- 0) Preflight --------
$server = "$SqlHost,$SqlPort"
Info "Target SQL Server: $server ; DB: $DbName"
Info "Root: $Root ; Bus: $Bus ; Lake: $Lake"

Ensure-Dir $Root
Ensure-Dir "$Root\ops\scripts"
Ensure-Dir "$Root\ops\config"

Ensure-Dir "$Lake\datasets"
Ensure-Dir "$Lake\artifacts"
Ensure-Dir "$Lake\evidence"
Ensure-Dir "$Lake\manifests"
Ensure-Dir "$Lake\quality"
Ensure-Dir "$Lake\lineage"

Ensure-Dir "$Bus\jobs"
Ensure-Dir "$Bus\cache"
Ensure-Dir "$Bus\tmp"

# -------- 1) Write dev.env --------
$devEnvPath = "$Root\ops\config\dev.env"
$devEnv = @"
# =========================
# AIWF dev.env (Windows)
# Generated by aiwf_one_shot_setup.ps1
# =========================

# ---- SQL Server (Control Plane) ----
AIWF_SQL_HOST=$SqlHost
AIWF_SQL_PORT=$SqlPort
AIWF_SQL_DB=$DbName
AIWF_SQL_USER=$AppUser
AIWF_SQL_PASSWORD=$AppPassword

# ---- Paths (Bus / Lake) ----
AIWF_ROOT=$Root
AIWF_BUS=$Bus
AIWF_LAKE=$Lake

# ---- Runtime ----
AIWF_ENV=dev
AIWF_LOG_LEVEL=INFO
AIWF_TIMEZONE=Asia/Shanghai

# ---- Dify / LLM (fill yourself) ----
AIWF_DIFY_BASE_URL=$DifyBaseUrl
AIWF_DIFY_API_KEY=$DifyApiKey
AIWF_LLM_PROVIDER=cloud
AIWF_LLM_MODEL=$LlmModel
AIWF_LLM_API_KEY=$LlmApiKey

# ---- accel-rust ----
AIWF_ACCEL_URL=http://127.0.0.1:18082
AIWF_ACCEL_OFFICE_MODE=fallback
AIWF_ACCEL_OFFICE_FORCE_PLACEHOLDER=false

# ---- Safety / Governance ----
AIWF_ALLOW_CLOUD_LLM=false
AIWF_LLM_FEED_MODE=stats_and_evidence
AIWF_PII_POLICY=mask

# ---- Ports for your services (suggested) ----
AIWF_BASE_JAVA_PORT=18080
AIWF_GLUE_PY_PORT=18081
AIWF_ACCEL_RUST_PORT=18082
"@
Write-Utf8NoBomFile $devEnvPath $devEnv
Ok "Wrote $devEnvPath"

# -------- 2) Canonical DB migration via db_migrate.ps1 --------
$migrateScript = "$Root\ops\scripts\db_migrate.ps1"
if (-not (Test-Path $migrateScript)) {
  throw "Canonical migration script not found: $migrateScript"
}

Info "Running canonical DB migration script..."
& powershell -ExecutionPolicy Bypass -File $migrateScript `
  -SqlHost $SqlHost `
  -SqlPort $SqlPort `
  -DbName $DbName `
  -SqlUser $SaUser `
  -SqlPassword $SaPassword `
  -Root $Root `
  -AppUser $AppUser `
  -AppPassword $AppPassword

if ($LASTEXITCODE -ne 0) {
  throw "db_migrate.ps1 failed with exit code $LASTEXITCODE"
}
Ok "Canonical DB migration completed."

# -------- 3) Self-test connection as app user --------
if (-not (Get-Command sqlcmd -ErrorAction SilentlyContinue)) {
  Warn "sqlcmd not found; skipped app-user self test"
} else {
  Info "Testing connection as $AppUser..."
  & sqlcmd -S $server -U $AppUser -P $AppPassword -b -Q "USE [$DbName]; SELECT TOP 10 name FROM sys.tables ORDER BY name;"
  if ($LASTEXITCODE -ne 0) {
    throw "self-test failed for app user $AppUser"
  }
  Ok "Self-test OK."
}

# -------- 4) Summary --------
Ok "All done."
Write-Host ""
Write-Host "=== Summary ==="
Write-Host "SQL Server : $server"
Write-Host "Database   : $DbName"
Write-Host "App User   : $AppUser"
Write-Host "dev.env    : $devEnvPath"
Write-Host "Bus        : $Bus"
Write-Host "Lake       : $Lake"

