use accel_rust::app_state::AppState;
use axum::{
    Router,
    routing::{get, post},
};

pub fn build_router(state: AppState) -> Router {
    Router::new()
        .route("/health", get(super::health))
        .route("/metrics", get(super::metrics))
        .route(
            "/admin/reload_runtime_config",
            post(super::reload_runtime_config),
        )
        .route("/operators/cleaning", post(super::cleaning_operator))
        .route(
            "/operators/compute_metrics",
            post(super::compute_metrics_operator),
        )
        .route(
            "/operators/transform_rows_v2",
            post(super::transform_rows_v2_operator),
        )
        .route(
            "/operators/transform_rows_v3",
            post(super::transform_rows_v3_operator),
        )
        .route(
            "/operators/transform_rows_v2/cache_stats",
            get(super::transform_rows_v2_cache_stats_operator),
        )
        .route(
            "/operators/transform_rows_v2/cache_clear",
            post(super::transform_rows_v2_cache_clear_operator),
        )
        .route(
            "/operators/transform_rows_v2/stream",
            post(super::transform_rows_v2_stream_operator),
        )
        .route(
            "/operators/transform_rows_v2/submit",
            post(super::transform_rows_v2_submit_operator),
        )
        .route(
            "/operators/text_preprocess_v2",
            post(super::text_preprocess_v2_operator),
        )
        .route(
            "/operators/join_rows_v1",
            post(super::join_rows_v1_operator),
        )
        .route(
            "/operators/join_rows_v2",
            post(super::join_rows_v2_operator),
        )
        .route(
            "/operators/join_rows_v3",
            post(super::join_rows_v3_operator),
        )
        .route(
            "/operators/normalize_schema_v1",
            post(super::normalize_schema_v1_operator),
        )
        .route(
            "/operators/entity_extract_v1",
            post(super::entity_extract_v1_operator),
        )
        .route(
            "/operators/aggregate_rows_v1",
            post(super::aggregate_rows_v1_operator),
        )
        .route(
            "/operators/aggregate_rows_v2",
            post(super::aggregate_rows_v2_operator),
        )
        .route(
            "/operators/aggregate_rows_v3",
            post(super::aggregate_rows_v3_operator),
        )
        .route(
            "/operators/quality_check_v1",
            post(super::quality_check_v1_operator),
        )
        .route(
            "/operators/quality_check_v2",
            post(super::quality_check_v2_operator),
        )
        .route(
            "/operators/quality_check_v3",
            post(super::quality_check_v3_operator),
        )
        .route(
            "/operators/aggregate_pushdown_v1",
            post(super::aggregate_pushdown_v1_operator),
        )
        .route(
            "/operators/plugin_exec_v1",
            post(super::plugin_exec_v1_operator),
        )
        .route(
            "/operators/plugin_health_v1",
            post(super::plugin_health_v1_operator),
        )
        .route(
            "/operators/plugin_registry_v1",
            post(super::plugin_registry_v1_operator),
        )
        .route(
            "/operators/plugin_operator_v1",
            post(super::plugin_operator_v1_operator),
        )
        .route(
            "/operators/rules_compile_v1",
            post(super::rules_compile_v1_operator),
        )
        .route(
            "/operators/rules_package_v1/publish",
            post(super::rules_package_publish_v1_operator),
        )
        .route(
            "/operators/rules_package_v1/get",
            post(super::rules_package_get_v1_operator),
        )
        .route(
            "/operators/load_rows_v1",
            post(super::load_rows_v1_operator),
        )
        .route(
            "/operators/load_rows_v2",
            post(super::load_rows_v2_operator),
        )
        .route(
            "/operators/load_rows_v3",
            post(super::load_rows_v3_operator),
        )
        .route(
            "/operators/save_rows_v1",
            post(super::save_rows_v1_operator),
        )
        .route(
            "/operators/schema_registry_v1/register",
            post(super::schema_registry_register_v1_operator),
        )
        .route(
            "/operators/schema_registry_v1/get",
            post(super::schema_registry_get_v1_operator),
        )
        .route(
            "/operators/schema_registry_v1/infer",
            post(super::schema_registry_infer_v1_operator),
        )
        .route(
            "/operators/schema_registry_v2/register",
            post(super::schema_registry_register_v2_operator),
        )
        .route(
            "/operators/schema_registry_v2/get",
            post(super::schema_registry_get_v2_operator),
        )
        .route(
            "/operators/schema_registry_v2/infer",
            post(super::schema_registry_infer_v2_operator),
        )
        .route(
            "/operators/schema_registry_v2/check_compat",
            post(super::schema_registry_check_compat_v2_operator),
        )
        .route(
            "/operators/schema_registry_v2/suggest_migration",
            post(super::schema_registry_suggest_migration_v2_operator),
        )
        .route(
            "/operators/udf_wasm_v1/apply",
            post(super::udf_wasm_v1_operator),
        )
        .route(
            "/operators/time_series_v1",
            post(super::time_series_v1_operator),
        )
        .route("/operators/stats_v1", post(super::stats_v1_operator))
        .route(
            "/operators/entity_linking_v1",
            post(super::entity_linking_v1_operator),
        )
        .route(
            "/operators/table_reconstruct_v1",
            post(super::table_reconstruct_v1_operator),
        )
        .route(
            "/operators/feature_store_v1/upsert",
            post(super::feature_store_upsert_v1_operator),
        )
        .route(
            "/operators/feature_store_v1/get",
            post(super::feature_store_get_v1_operator),
        )
        .route("/operators/lineage_v2", post(super::lineage_v2_operator))
        .route(
            "/operators/rule_simulator_v1",
            post(super::rule_simulator_v1_operator),
        )
        .route(
            "/operators/constraint_solver_v1",
            post(super::constraint_solver_v1_operator),
        )
        .route(
            "/operators/chart_data_prep_v1",
            post(super::chart_data_prep_v1_operator),
        )
        .route(
            "/operators/diff_audit_v1",
            post(super::diff_audit_v1_operator),
        )
        .route(
            "/operators/vector_index_v1/build",
            post(super::vector_index_build_v1_operator),
        )
        .route(
            "/operators/vector_index_v1/search",
            post(super::vector_index_search_v1_operator),
        )
        .route(
            "/operators/evidence_rank_v1",
            post(super::evidence_rank_v1_operator),
        )
        .route(
            "/operators/fact_crosscheck_v1",
            post(super::fact_crosscheck_v1_operator),
        )
        .route(
            "/operators/timeseries_forecast_v1",
            post(super::timeseries_forecast_v1_operator),
        )
        .route(
            "/operators/finance_ratio_v1",
            post(super::finance_ratio_v1_operator),
        )
        .route(
            "/operators/anomaly_explain_v1",
            post(super::anomaly_explain_v1_operator),
        )
        .route(
            "/operators/template_bind_v1",
            post(super::template_bind_v1_operator),
        )
        .route(
            "/operators/provenance_sign_v1",
            post(super::provenance_sign_v1_operator),
        )
        .route(
            "/operators/stream_state_v1/save",
            post(super::stream_state_save_v1_operator),
        )
        .route(
            "/operators/stream_state_v1/load",
            post(super::stream_state_load_v1_operator),
        )
        .route(
            "/operators/query_lang_v1",
            post(super::query_lang_v1_operator),
        )
        .route(
            "/operators/columnar_eval_v1",
            post(super::columnar_eval_v1_operator),
        )
        .route(
            "/operators/stream_window_v1",
            post(super::stream_window_v1_operator),
        )
        .route(
            "/operators/stream_window_v2",
            post(super::stream_window_v2_operator),
        )
        .route("/operators/sketch_v1", post(super::sketch_v1_operator))
        .route(
            "/operators/runtime_stats_v1",
            post(super::runtime_stats_v1_operator),
        )
        .route(
            "/operators/capabilities_v1",
            post(super::capabilities_v1_operator),
        )
        .route(
            "/operators/io_contract_v1/validate",
            post(super::io_contract_v1_operator),
        )
        .route(
            "/operators/failure_policy_v1",
            post(super::failure_policy_v1_operator),
        )
        .route(
            "/operators/incremental_plan_v1",
            post(super::incremental_plan_v1_operator),
        )
        .route(
            "/operators/tenant_isolation_v1",
            post(super::tenant_isolation_v1_operator),
        )
        .route(
            "/operators/operator_policy_v1",
            post(super::operator_policy_v1_operator),
        )
        .route(
            "/operators/optimizer_adaptive_v2",
            post(super::optimizer_adaptive_v2_operator),
        )
        .route(
            "/operators/vector_index_v2/build",
            post(super::vector_index_build_v2_operator),
        )
        .route(
            "/operators/vector_index_v2/search",
            post(super::vector_index_search_v2_operator),
        )
        .route(
            "/operators/vector_index_v2/eval",
            post(super::vector_index_eval_v2_operator),
        )
        .route(
            "/operators/stream_reliability_v1",
            post(super::stream_reliability_v1_operator),
        )
        .route(
            "/operators/lineage_provenance_v1",
            post(super::lineage_provenance_v1_operator),
        )
        .route(
            "/operators/contract_regression_v1",
            post(super::contract_regression_v1_operator),
        )
        .route(
            "/operators/perf_baseline_v1",
            post(super::perf_baseline_v1_operator),
        )
        .route(
            "/operators/window_rows_v1",
            post(super::window_rows_v1_operator),
        )
        .route(
            "/operators/optimizer_v1",
            post(super::optimizer_v1_operator),
        )
        .route(
            "/operators/join_rows_v4",
            post(super::join_rows_v4_operator),
        )
        .route(
            "/operators/aggregate_rows_v4",
            post(super::aggregate_rows_v4_operator),
        )
        .route(
            "/operators/quality_check_v4",
            post(super::quality_check_v4_operator),
        )
        .route("/operators/lineage_v3", post(super::lineage_v3_operator))
        .route(
            "/operators/parquet_io_v2",
            post(super::parquet_io_v2_operator),
        )
        .route(
            "/operators/stream_state_v2",
            post(super::stream_state_v2_operator),
        )
        .route(
            "/operators/udf_wasm_v2/apply",
            post(super::udf_wasm_v2_operator),
        )
        .route(
            "/operators/explain_plan_v1",
            post(super::explain_plan_v1_operator),
        )
        .route(
            "/operators/explain_plan_v2",
            post(super::explain_plan_v2_operator),
        )
        .route("/metrics_v2", get(super::metrics_v2))
        .route("/metrics_v2/prom", get(super::metrics_v2_prom))
        .route("/workflow/run", post(super::workflow_run_operator))
        .route("/tasks/{task_id}", get(super::get_task_operator))
        .route("/tasks/{task_id}/cancel", post(super::cancel_task_operator))
        .with_state(state)
}
