use accel_rust::app_state::AppState;
use axum::{Router, routing::post};

pub(super) fn governance_routes() -> Router<AppState> {
    Router::new()
        .route(
            "/operators/runtime_stats_v1",
            post(crate::http::runtime_stats_v1_operator),
        )
        .route(
            "/operators/capabilities_v1",
            post(crate::http::capabilities_v1_operator),
        )
        .route(
            "/operators/io_contract_v1/validate",
            post(crate::http::io_contract_v1_operator),
        )
        .route(
            "/operators/failure_policy_v1",
            post(crate::http::failure_policy_v1_operator),
        )
        .route(
            "/operators/incremental_plan_v1",
            post(crate::http::incremental_plan_v1_operator),
        )
        .route(
            "/operators/tenant_isolation_v1",
            post(crate::http::tenant_isolation_v1_operator),
        )
        .route(
            "/operators/operator_policy_v1",
            post(crate::http::operator_policy_v1_operator),
        )
        .route(
            "/operators/optimizer_adaptive_v2",
            post(crate::http::optimizer_adaptive_v2_operator),
        )
        .route(
            "/operators/vector_index_v2/build",
            post(crate::http::vector_index_build_v2_operator),
        )
        .route(
            "/operators/vector_index_v2/search",
            post(crate::http::vector_index_search_v2_operator),
        )
        .route(
            "/operators/vector_index_v2/eval",
            post(crate::http::vector_index_eval_v2_operator),
        )
        .route(
            "/operators/stream_reliability_v1",
            post(crate::http::stream_reliability_v1_operator),
        )
        .route(
            "/operators/lineage_provenance_v1",
            post(crate::http::lineage_provenance_v1_operator),
        )
        .route(
            "/operators/contract_regression_v1",
            post(crate::http::contract_regression_v1_operator),
        )
        .route(
            "/operators/perf_baseline_v1",
            post(crate::http::perf_baseline_v1_operator),
        )
}
